sudo: required

language: generic

services:
  - docker

env:
  global:
    - secure: Ryi00VkGn9zMG3rOTViiApUPPy6Qu38YAe6ypc0rfxfsjREJgE9UsiDLS5FBVpcjrxP42CMqiy3XAxz1S9/RB0J/9xR2fWoaoeOgKdOpkdJYlzAxlout+u8drhO9DvmCKBo0GILVnsoZ1QcDNQpzLP/lfulEyfc/ZsiuJcMcISpwDMEb7iCpa8gBMJFAL2EjhABuSfiEeqpWGJCgI0KZo4j/pfi0fN1bWRL8gChLGIhoeJmdxPFBDE6yYERfmVoxxLIZ7vL3wsa0ulwmKv2fOgaHR3QNoB7AT6yzF+uhFfjM0VwGqw41vFDdMIp1uY27rh+Vys4BxcFrr+0BFa0fqVaZn3XFO8NQIFWz0OAtKieCne22KDKFXDHcnCHlvoZgGGy1L5+1zWeqaR/acwnWfUEvxJJdKZ5sJffjaBY1LYkOsyeywWVR73MjHMwZmtWPdTp1/0kRc/jN+IKKO4S8jfHk5Wj68+NsllrzpiMDJNtINPDB1w1yjHzXSkFJevJjFvEtvB+DEmCDLUEyPmx2+HdlcNEsdb6S8LNdJyszKi4vbsWhFYoxjsZ7bNE+3zpMrigZydA21iTkUSID1RSYDgCSxdXhhZskM5nQ3O4UXGhsIlrZqTX1vJ45d0l3k+dvEGizLsabVoJG+Gw+iL5Hg85H4cm8teDanDgeZsbKgAg=
    - secure: KKRWVon8TgVSVwWM7RqfzuxM5dNxRkxHRjOeWIeQEcOpOyvF00VRowD2tXgQdcOjPX1dzW8TrgmHv0ddaCxHc8JBnIDCNWhKvgybBXgG7W19adoCM1OGX+4Qrw7m+21Dha4khpSNVrMXSres9620pcU50JXsLj1PIDh15tcuv+wVnP25GoRUHgPaHwWf8faDGWx0y95quF+XATibPNcdnKdzzF4BDTj+SZFy0TIWmlp9PYnrealtZUGMOHV22C5pt/9A49SUxNyPfFsBCyrM5elalOPDG42oUm+2Q7OUTIZgiF0s4eY/xUfGmz/TX61g+j4M2B5osKOT1+pPNX0p8UYKAh8K3Botvw29/WQcYRrE3SpKoCT3YYr5kflIyCW5ulBy3A1MZvAXbIqm47/Q/dbmPvEhIsctstBSMZz+vP1AtYF+/KxzZxQBs3WPf87sUshJxEHO+2B2SNDUwsX9i1n3/iCMMGSNAYv7ek+momHX/SNpdALC+HtmXzR0AfvbWSVihoHZ9dEGWDsN00eAoOyXXkClaravN3tO0Dm0eitAdQZVHmvixLGfCnHP9j91r5eTuZ4DqXSD2YAzesPXvCzOTd4nYa9PFJ8+eOTgaRXtG6WqC7PLTNP2j3g6sR0R/D/p5wYa3aEQpQLScVOuW5zbah3UC6hXDVpHxHAlGKY=
    - COMMIT=${TRAVIS_COMMIT::8}

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=nestyurkin/samba4timemachine
  - docker build -f Dockerfile -t $REPO:$COMMIT --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` .
  - docker tag $REPO:$COMMIT $REPO:latest
  - docker push $REPO
